project:
  type: website

website:
  title: "Ethan Long â€“ Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects/clutch-gene.qmd
            text: Clutch Gene
          - href: projects/nyc-311.qmd
            text: NYC 311 Flooding Complaints
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
