project:
  type: website
  output-dir: docs
website:
  title: "Ethan Long â€“ Portfolio"
  description: 'Data Science Portfolio highlighting projects in predictive modeling, sports analytics, and machine learning.'
  site-url: 'https://Ethan964.github.io/ethan-portfolio'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects/clutch-gene.qmd
            text: Clutch Gene
          - href: projects/nyc-311.qmd
            text: NYC 311 Flooding Complaints
          - href: projects/boston_311.qmd
            text: Boston 311 Responsiveness
format:
  html:
    theme: none
    css: styles.css
    toc: true
